// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gurqcivvexqgwjvyifzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cnFjaXZ2ZXhxZ3dqdnlpZnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDYyMTAsImV4cCI6MjA3MDIyMjIxMH0.Fv0f4sMF4ZUAfcb_HEhXnAz-i13wTWp6Obt3teu2Y5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});